### ISSUE TITLE
Checksum Incorrect

### ISSUE THREAD

**Issue by mbwmbw1337** [CoinMetro/API-DOCS#2]
I believe the checksum CRC32 is incorrect that’s being provided if indeed the key value pairs are sorted in lexicographical order. I’ve spent hours troubleshooting this and I am getting a different CRC most the time. Would you be able to double check that code and confirm the CRC string is correctly being generated? It’d help if the api response would have the underlying concatenated string so I could compare to figure out where the difference is...

**Comment by salvatore-fxpig** [comment]
Solved by https://github.com/CoinMetro/API-DOCS/commit/5cb5f6a759b7d3ccec953623e01e61de504b3a3a
